import { type RouteConfig, index, route } from "@react-router/dev/routes";
export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("logout", "routes/logout.tsx"),
  route("settings", "routes/settings.tsx"),
  route("explore", "routes/explore.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/analytics", "routes/admin.analytics.tsx"),
  route("admin/users", "routes/admin.users.tsx"),
  route("admin/posts", "routes/admin.posts.tsx"),
  route("admin/comments", "routes/admin.comments.tsx"),
  route("users/:username", "routes/users.$username.tsx"),
  route("users/:username/:type", "routes/users.$username.$type.tsx"),
  route("users/:username/likes", "routes/users.$username.likes.tsx"),
  route("search", "routes/search.tsx"),
  route("notifications", "routes/notifications.tsx"),
  route("bookmarks", "routes/bookmarks.tsx"),
  route("messages", "routes/messages.tsx"),
  route("posts/:postId", "routes/posts.$postId.tsx"),
  route("posts/:postId/interactions", "routes/posts.$postId.interactions.tsx"),
  route("hashtag/:tag", "routes/hashtag.$tag.tsx"),
  route("api/posts/create", "routes/api.posts.create.tsx"),
  route("api/posts/:postId/like", "routes/api.posts.$postId.like.tsx"),
  route("api/posts/:postId/bookmark", "routes/api.posts.$postId.bookmark.tsx"),
  route("api/posts/:postId/delete", "routes/api.posts.$postId.delete.tsx"),
  route("api/comments/create", "routes/api.comments.create.tsx"),
  route("api/comments/:commentId/delete", "routes/api.comments.$commentId.delete.tsx"),
  route("api/users/:userId/follow", "routes/api.users.$userId.follow.tsx"),
  route("api/feed/forYou", "routes/api.feed.forYou.tsx"),
  route("api/feed/following", "routes/api.feed.following.tsx")
] satisfies RouteConfig;